- name: check a number less than 10 or not
  hosts: local
  # vars_prompt:
  # - name: number
  #   prompt: "Enter a number"
  #   private: false
  vars:
    number: 120
  tasks:
    - name: check if number is less than 10
      ansible.builtin.debug:
        msg: "The number {{ number }} is less than 10"
      when: number < 10

    - name: check if number i greater than or equal to 10
      ansible.builtin.debug:
        msg: "The nuber {{ number }} is greater than or equal to 10"
      when: number >= 10
