- name: install nginx
  hosts: web
  become: true
  tasks:
    - name: print the stats
      ansible.builtin.debug:
       msg: "{{ ansible_facts }}"

    - name: install nginx if redhat
      ansible.builtin.yum:
        name: nginx
        state: present
      when: ansible_os_family == "RedHat"

    - name: install nginx if debian
      ansible.builtin.apt:
        name: nginx
        state: present
      when: ansible_os_family == "Debian"
  