- name: loops demo
  hosts: local
  connection: local
  tasks:
  - name: print names
    ansisble.builtin.debug:
     msg: "Hello, {{ item }} "
    loop:
    - Ramesh
    - Suresh
    - Rahim
    - Robert