- name: intall tomcat, nginx, mysql
  hosts: web
  become: true
  tasks:
    - name: install multiple packages
      ansible.builtin.package:
        name: " {{ item}} "
        state: present
      loop:
      - tomcat
      - nginx
      - mysql-server
      - git